### ISSUE TITLE
 Video and Image Scale Problem

### ISSUE THREAD

**Issue by alicankurt1** [tiskender2/StoryUI#5]
First of all, thank you for the library. 

(Selamlar) How to change/fix scaleToFill or scaleToFit stories media. When upload a image or video, media sizes look distorted.

![Ekran Resmi 2022-06-29 11 26 19](https://user-images.githubusercontent.com/20724649/176389907-de463614-e436-4cd6-81af-f22fcb77d97e.png)

Should look like this ;

![Ekran Resmi 2022-06-29 11 29 03](https://user-images.githubusercontent.com/20724649/176390115-41369070-f60f-4fbf-87ca-86d55bffc751.png)

**Comment by tiskender2** [comment]
Hello,
you should change your image  its not suitable
prefer vertical images rather than horizontal

**Comment by alicankurt1** [comment]
> Hello, you should change your image its not suitable prefer vertical images rather than horizontal

Thanks for your answer, but I'm not the one to choose the image, users. So can I edit it as Scale to Fit instead of scale to Fill?

**Comment by tiskender2** [comment]
yes you can change from source code, its up to you
to do that you need to download source code  instead of using SPM
