### ISSUE TITLE
Overlapping of Video Sounds

### ISSUE THREAD

**Issue by alicankurt1** [tiskender2/StoryUI#6]
Each time the video story is opened, so many sounds overlap. 

Can this situation be fixed easily?

**Comment by tiskender2** [comment]
Hi alicankurt1
Could you please provide example

**Comment by alicankurt1** [comment]
Ofcourse,

https://www.youtube.com/shorts/eSdfcd7Xk68

When I close the Story and open it again and again, the same problem occurs.

**Comment by alicankurt1** [comment]
Hi Iskender,

Were you able to detect the problem?

**Comment by tiskender2** [comment]
Hi @alicankurt1 
sorry for late response mean time i have fixed video overlapping problem and relaesed version 1.1.0 
if there is still bugs dont hesitate to open issue have fun
